### ISSUE TITLE
Complete vision, meet, and it-takes-a-volunteer pages

### ISSUE THREAD

**Issue by pikemurdy** [utkwdn/utk-atlas#47]
The meet page has a function which opens a modal when scrolled halfway down the page.
Functionality can be seen here: http://www.utk.edu/meet/

That currently doesn't work at http://dev.cms.utk.edu/meet

The vision page has some javascript created animation, functionality can be seen here: https://www.utk.edu/vision

That is currently not working here: https://dev.cms.utk.edu/vision

**Comment by spworky** [comment]
@pikemurdy I think the vision page can be added in as a static page, the same way I did the It takes a volunteer. I think I have that partially setup.

**Comment by MichaelAllenWarner** [comment]
All three of these may have JavaScript requirements, but none need to pull data or markup from WordPress.

**Comment by pikemurdy** [comment]
`/ittakesavolunteer/` - static page (content not in WordPress). Based on `https://www.utk.edu/ittakesavolunteer`

[ ] The URL needs to remain `https://www.utk.edu/ittakesavolunteer`

**Comment by MichaelAllenWarner** [comment]
`/meet` page has a "sign up for our mailing list" button at the bottom that should be opening a modal

**Comment by MichaelAllenWarner** [comment]
We'll delete the `/itav` component-page and just use the static version of the `/ittakesavolunteer` page.

We'll restore the static version of `/vision`, and we'll try to set the corresponding Reactified version to not build (so that we can preserve the code, since we might want to use it later).

**Comment by MichaelAllenWarner** [comment]
To do:

- [ ] delete the `/itav` component-page
- [ ] restore the static version of `/vision` (but don't delete the Reactified version of it; see next item)
- [ ] if possible, prevent Next.js from building the Reactified version of the `/vision` page, but without actually removing the file from the codebase (try https://nextjs.org/docs/api-reference/data-fetching/get-static-props#notfound)
- [ ] get "sign up for our mailing list" modal working on the Reactified version of the `/meet` page (which otherwise is done, we think)
- [ ] once everything else is done, verify that all 3 of these pages look and function as intended
